### ISSUE TITLE
How access bundled data?

### ISSUE THREAD

**Issue by twMat** [OokTech/TW5-FederationCore#4]
Not your task but maybe you have some ideas - plus I guess it shows some needs from a user:

Do you have any good ideas for how to extract data from the bundle? The only strategy I can come up with is iterating the whole bundle through a recursive filter to split out one field at a time by means of e.g `splitbefore[name:]` etc. But this would be so brittle it is not even worth trying. (Do fields even follow a strict order? I believe json tiddlers can have their fields in any order. Plus there may be custom fields of course...)

What I want to do is create "preview cards" as per my TWederBob UI showing some of the tiddlers data.

**Comment by inmysocks** [comment]
It depends on what you want the preview cards for. For just fetching tiddlers from a known wiki I doubt that preview cards are very useful. So what is the context?

For special contexts it is probably better to create a separate handler function, which wouldn't be part of the core because this is just the primitives needed for the basic function.

**Comment by twMat** [comment]
The idea is to have a consistent UI regardless if one fetches from separate wikis (using FedCore) or a server (using TWederBob). The UI should give the option to see some meta data about a tiddler before actually unbundling or importing it. For e.g friends comments this is not relevant but when fetching less personal things like plugins, themes, macros, code snips, stylesheets, palettes, ... Things that do well with a "presentation" explaining them even if just  "Snow White - emphasizes individual tiddlers".

Currently, the user can only get information from looking at the titles or he must "manually" inspect the bundle.

>For special contexts it is probably better to create a separate handler function, which wouldn't be part of the core because this is just the primitives needed for the basic function.

This goes beyond my skills. Is this something you could do?

**Comment by inmysocks** [comment]
These are just the basic tools, they are not meant to be the application itself. they are meant to be used by other applications. What you are describing is an application that uses this, not part of this by itself because it isn't something necessary to everything that uses the FederationCore plugin.

**Comment by twMat** [comment]
You're of course right. I can only speak with certainty about my own needs *but* I have a hard time seeing how anyone will be able to build anything on top of your plugin (...using wikitext, not js) if they cannot access the bundled tiddlers data.

**Comment by inmysocks** [comment]
This is what we were using for the conveersatiens thing we had before. And this is the primitives, nothing more.

If you want more it would be in another plugin.

**Comment by twMat** [comment]
OK then.
Thanks for your replies.
